name: >Pytest

on: [push]

jobs:
  build:
  
    run-on: ubuntu-lastest
    strategy:
      matrix:
        python-version: [2.7,3.5,3.6,3.7,3.8]
      
    steps:
    - uses: actions/checkout@v2
    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.text ]; then pip install -r requirements.text; fi
     - name: Test with pytest
       run: |
       pytest
